// app/insights/page.tsx
"use client";

import { useState, useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
import { RootState } from "@/store/index";
import { deleteInsight, setInsights } from "@/store/insightsSlice";

// --- Types ---
export interface Insight {
    id: string;
    type: "system" | "ai" | "psychologist";
    title: string;
    preview: string;
    content: string;
    category: string;
    timestamp: string;
    isRead: boolean;
    isNew?: boolean;
}

// --- Helper Functions ---
const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString("en-US", {
        weekday: "short",
        month: "short",
        day: "numeric",
        year: "numeric",
    });
};

const getTimeAgo = (dateString: string) => {
    const now = new Date();
    const then = new Date(dateString);
    const diffMs = now.getTime() - then.getTime();
    const diffMin = Math.floor(diffMs / 60000);
    const diffHr = Math.floor(diffMs / 3600000);
    const diffDay = Math.floor(diffMs / 86400000);

    if (diffMin < 1) return "Just now";
    if (diffMin < 60) return `${diffMin}m ago`;
    if (diffHr < 24) return `${diffHr}h ago`;
    if (diffDay < 7) return `${diffDay}d ago`;
    return formatDate(dateString);
};

// --- Mock Data ---
const mockInsights: Insight[] = [
    {
        id: "1",
        type: "psychologist",
        title: "New Response",
        preview: '"It sounds like you are carrying a lot of tension from work. When the mind feels crowded, try returning to the body. Five deep breaths, focusing only on the exhale, can help reset your nervous system."',
        content: `It sounds like you are carrying a lot of tension from work. When the mind feels crowded, try returning to the body.\n\nFive deep breaths, focusing only on the exhale, can help reset your nervous system.\n\nThis technique, called diaphragmatic breathing, activates the parasympathetic nervous system and signals to your brain that you are safe. Over time, this practice can rewire your stress response.\n\nI'd like you to try this for 3 minutes each morning and before bed. Let me know how it feels in our next session.\n\n— Dr. Sarah Chen, Licensed Psychologist`,
        category: "Grounding",
        timestamp: "2026-07-22T14:30:00Z",
        isRead: false,
        isNew: true,
    },
    {
        id: "2",
        type: "ai",
        title: "Stress Pattern Detected",
        preview: "We've noticed an increase in stress-related language in your journal entries over the past 3 days.",
        content: `Pattern detected: Your journal entries from the past 3 days show a 42% increase in stress-related vocabulary compared to your baseline.\n\nCommon themes include: overwhelmed, pressure, deadline, exhausted.\n\nRecommendation: Schedule two 10-minute mindfulness breaks today. Try the "5-4-3-2-1" grounding technique:\n• 5 things you can see\n• 4 things you can touch\n• 3 things you can hear\n• 2 things you can smell\n• 1 thing you can taste\n\nThis can help interrupt the stress cycle and bring you back to the present moment.`,
        category: "Stress Management",
        timestamp: "2026-07-21T09:15:00Z",
        isRead: false,
        isNew: true,
    },
    {
        id: "3",
        type: "system",
        title: "Weekly Progress Summary",
        preview: "You completed 4 mindfulness sessions this week. Your overall mood score improved by 12%.",
        content: `Week of July 19 – July 25\n\nHere's your weekly progress summary:\n• Mindfulness sessions: 4 completed (target: 5)\n• Mood score: 7.2/10 (↑12% from last week)\n• Journal entries: 6 entries (↑2 from last week)\n• Stress level: Moderate (↓8% from last week)\n\nYou're making steady progress! Keep up the consistency — the data shows that your mindfulness practice is directly correlated with improved mood stability.\n\n📊 Generated by your Wellness Dashboard`,
        category: "Progress",
        timestamp: "2026-07-20T23:59:00Z",
        isRead: true,
        isNew: false,
    },
];

// --- Main Component ---
export default function InsightsPage() {
    const dispatch = useDispatch();
    const insights = useSelector((state: RootState) => state.insights?.insights || []);
    const [isClient, setIsClient] = useState(false);

    // Load insights on client side only
    useEffect(() => {
        setIsClient(true);
        if (insights.length === 0) {
            dispatch(setInsights(mockInsights));
        }
    }, [dispatch, insights.length]);

    const displayInsights = insights.length > 0 ? insights : mockInsights;

    const handleDeleteInsight = (id: string) => {
        if (window.confirm("Delete this insight?")) {
            dispatch(deleteInsight(id));
        }
    };

    const getTypeLabel = (type: Insight["type"]) => {
        switch (type) {
            case "psychologist":
                return "Psychologist";
            case "ai":
                return "AI Insight";
            case "system":
                return "System";
            default:
                return "Update";
        }
    };

    const sortedInsights = [...displayInsights].sort(
        (a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()
    );

    if (!isClient) {
        return (
            <div className="min-h-screen bg-gradient-to-br from-amber-50/50 via-white to-orange-50/30">
                <div className="max-w-4xl mx-auto px-4 sm:px-6 py-8 md:py-12">
                    <h1 className="text-2xl md:text-3xl font-bold tracking-tight text-slate-900">
                        Insights Inbox
                    </h1>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-gradient-to-br from-amber-50/50 via-white to-orange-50/30">
            <div className="max-w-4xl mx-auto px-4 sm:px-6 py-8 md:py-12">
                {/* Header */}
                <div className="mb-8">
                    <p className="text-sm text-amber-700/60">
                        Professional Guidance
                    </p>
                    <div className="flex items-center gap-3 mb-1">
                        <h1 className="text-2xl md:text-3xl font-bold tracking-tight text-slate-900">
                            Insights Inbox
                        </h1>
                    </div>
                </div>

                {/* Insights List */}
                <div className="bg-white rounded-2xl shadow-lg border border-slate-200/80 overflow-hidden">
                    {sortedInsights.length === 0 ? (
                        <div className="text-center py-12">
                            <p className="text-sm text-slate-400">No insights yet</p>
                        </div>
                    ) : (
                        <div className="divide-y divide-slate-100">
                            {sortedInsights.map((insight) => {
                                return (
                                    <div
                                        key={insight.id}
                                        className="p-4 md:p-5 bg-[#1C1A17]"
                                    >
                                        <div className="flex items-start gap-3">
                                            <div className="flex-1 min-w-0">
                                                <div className="flex items-center gap-2">
                                                    <h3 className="font-medium text-amber-700/60">
                                                        {insight.title}
                                                    </h3>
                                                </div>
                                                <p className="text-sm line-clamp-2 mt-0.5 text-white/80">
                                                    {insight.preview}
                                                </p>
                                                <div className="flex items-center gap-3 mt-2">
                                                    <span className="text-xs text-white/40">
                                                        {getTypeLabel(insight.type)}
                                                    </span>
                                                    <span className="text-xs text-white/40">
                                                        {getTimeAgo(insight.timestamp)}
                                                    </span>
                                                    <span className="text-xs text-white/40">
                                                        {insight.category}
                                                    </span>
                                                </div>
                                            </div>
                                            <button
                                                onClick={() => handleDeleteInsight(insight.id)}
                                                className="flex-shrink-0 p-1.5 rounded-lg hover:bg-red-500/20 text-white/40 hover:text-red-400 transition-colors"
                                                title="Delete"
                                            >
                                                <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                                </svg>
                                            </button>
                                        </div>
                                    </div>
                                );
                            })}
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}